[2016-09-11 10:22:49,076: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-11 10:22:49,082: INFO/MainProcess] mingle: searching for neighbors
[2016-09-11 10:22:50,088: INFO/MainProcess] mingle: all alone
[2016-09-11 10:22:50,099: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-11 10:22:50,099: WARNING/MainProcess] w1@Rui ready.
[2016-09-11 10:22:50,100: INFO/MainProcess] Received task: sms.tasks.add[26507175-9f60-4549-8cf3-42ecfb027635]
[2016-09-11 10:22:50,101: INFO/MainProcess] Task sms.tasks.add[26507175-9f60-4549-8cf3-42ecfb027635] succeeded in 0.00036139099938736763s: 8
[2016-09-11 10:23:07,823: INFO/MainProcess] Received task: sms.tasks.add[b1ef18a8-9ead-4280-b734-48deebb39a76]
[2016-09-11 10:23:07,825: INFO/MainProcess] Task sms.tasks.add[b1ef18a8-9ead-4280-b734-48deebb39a76] succeeded in 0.0008212630000343779s: 8
[2016-09-11 10:23:15,630: INFO/MainProcess] Received task: sms.tasks.add[c2e5d394-0ee6-4c75-a2e9-c532c03779e7]
[2016-09-11 10:23:15,636: INFO/MainProcess] Task sms.tasks.add[c2e5d394-0ee6-4c75-a2e9-c532c03779e7] succeeded in 0.00281229699976393s: 8
[2016-09-11 10:23:32,580: INFO/MainProcess] Received task: sms.tasks.add[291b2918-1b09-4bf8-ad67-1c56d4df2ecf]
[2016-09-11 10:23:32,581: INFO/MainProcess] Task sms.tasks.add[291b2918-1b09-4bf8-ad67-1c56d4df2ecf] succeeded in 0.0008549310005037114s: 8
[2016-09-11 23:28:41,691: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-11 23:28:41,701: INFO/MainProcess] mingle: searching for neighbors
[2016-09-11 23:28:42,708: INFO/MainProcess] mingle: all alone
[2016-09-11 23:28:42,722: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-11 23:28:42,722: WARNING/MainProcess] w1@Rui ready.
[2016-09-11 23:28:42,723: INFO/MainProcess] Received task: sms.tasks.add[393340af-9097-4926-9c01-a9ac5b2aa2ec]
[2016-09-11 23:28:42,724: INFO/MainProcess] Task sms.tasks.add[393340af-9097-4926-9c01-a9ac5b2aa2ec] succeeded in 0.000337672000114253s: 8
[2016-09-11 23:28:44,715: INFO/MainProcess] Received task: sms.tasks.add[bcb01a1b-8adf-49c6-975e-f48f365e0a98]
[2016-09-11 23:28:44,716: INFO/MainProcess] Received task: sms.tasks.add[6b26b0fe-3366-42cf-9c88-4df6390c723c]
[2016-09-11 23:28:44,716: INFO/MainProcess] Received task: sms.tasks.add[890b5f89-c81f-4401-8828-823f6fc9034b]
[2016-09-11 23:28:44,716: INFO/MainProcess] Received task: sms.tasks.add[f9f2b985-4dd5-4336-b02f-a5e0b8284808]
[2016-09-11 23:28:44,717: INFO/MainProcess] Task sms.tasks.add[6b26b0fe-3366-42cf-9c88-4df6390c723c] succeeded in 0.00036212099985277746s: 8
[2016-09-11 23:28:44,717: INFO/MainProcess] Task sms.tasks.add[f9f2b985-4dd5-4336-b02f-a5e0b8284808] succeeded in 0.000638617000049635s: 8
[2016-09-11 23:28:44,717: INFO/MainProcess] Task sms.tasks.add[890b5f89-c81f-4401-8828-823f6fc9034b] succeeded in 0.0007805350001035549s: 8
[2016-09-11 23:28:44,718: INFO/MainProcess] Task sms.tasks.add[bcb01a1b-8adf-49c6-975e-f48f365e0a98] succeeded in 0.0009170239998184115s: 8
[2016-09-11 23:28:47,929: INFO/MainProcess] Received task: sms.tasks.add[91fcc0b0-c52c-4401-b6fa-2827e63b5d9d]
[2016-09-11 23:28:47,930: INFO/MainProcess] Task sms.tasks.add[91fcc0b0-c52c-4401-b6fa-2827e63b5d9d] succeeded in 0.0003995350000423059s: 8
[2016-09-11 23:31:29,110: INFO/MainProcess] Received task: sms.tasks.send_message[0927b8d8-3941-408e-bb01-7c4a78030cba]
[2016-09-11 23:31:30,606: WARNING/Worker-2] Message has been sent
[2016-09-11 23:31:30,607: INFO/MainProcess] Task sms.tasks.send_message[0927b8d8-3941-408e-bb01-7c4a78030cba] succeeded in 1.4968673870000657s: None
[2016-09-11 23:37:19,036: INFO/MainProcess] Received task: sms.tasks.send_message[43cc8fd9-458d-499e-bab1-868bbe078204]
[2016-09-11 23:37:20,812: WARNING/Worker-4] Message has been sent
[2016-09-11 23:37:20,813: INFO/MainProcess] Task sms.tasks.send_message[43cc8fd9-458d-499e-bab1-868bbe078204] succeeded in 1.7762591939999766s: None
[2016-09-11 23:38:27,125: INFO/MainProcess] Received task: sms.tasks.send_message[1d5adfcc-74d8-40da-abbd-1233a0926b63] eta:[2016-09-12 09:39:27.094289+10:00]
[2016-09-11 23:39:29,538: WARNING/Worker-8] Message has been sent
[2016-09-11 23:39:29,538: INFO/MainProcess] Task sms.tasks.send_message[1d5adfcc-74d8-40da-abbd-1233a0926b63] succeeded in 1.9107827590000852s: None
[2016-09-12 00:22:39,638: INFO/MainProcess] Received task: sms.tasks.add[0c9132d9-0603-47b8-8681-acace270aa1c]
[2016-09-12 00:22:39,640: INFO/MainProcess] Task sms.tasks.add[0c9132d9-0603-47b8-8681-acace270aa1c] succeeded in 0.00043559799996728543s: 8
[2016-09-12 00:35:22,853: INFO/MainProcess] Received task: sms.tasks.add[a0f9602c-572b-4e3c-a8ec-1f64f8218127]
[2016-09-12 00:35:22,854: INFO/MainProcess] Task sms.tasks.add[a0f9602c-572b-4e3c-a8ec-1f64f8218127] succeeded in 0.0005870430004506488s: 8
[2016-09-12 00:38:23,294: INFO/MainProcess] Received task: sms.tasks.add[077069dd-b10b-4df0-9b91-da903e2bc7fa]
[2016-09-12 00:38:23,297: INFO/MainProcess] Task sms.tasks.add[077069dd-b10b-4df0-9b91-da903e2bc7fa] succeeded in 0.0009744390008563641s: 8
[2016-09-12 01:11:59,633: INFO/MainProcess] Received task: sms.tasks.add[b040bab5-3565-472b-8514-e6387a03d528]
[2016-09-12 01:11:59,635: INFO/MainProcess] Task sms.tasks.add[b040bab5-3565-472b-8514-e6387a03d528] succeeded in 0.0009237649992428487s: 8
[2016-09-12 01:46:06,524: INFO/MainProcess] Received task: sms.tasks.add[d59a8e90-4986-4f12-bdc6-ae0f5d315f40]
[2016-09-12 01:46:06,525: INFO/MainProcess] Task sms.tasks.add[d59a8e90-4986-4f12-bdc6-ae0f5d315f40] succeeded in 0.0003899530001945095s: 8
[2016-09-12 01:48:53,077: INFO/MainProcess] Received task: sms.tasks.add[d8aed9b2-80e7-4b23-8d1c-0461f6c01a9f]
[2016-09-12 01:48:53,078: INFO/MainProcess] Task sms.tasks.add[d8aed9b2-80e7-4b23-8d1c-0461f6c01a9f] succeeded in 0.00026959999922837596s: 8
[2016-09-12 01:48:53,361: INFO/MainProcess] Received task: sms.tasks.add[f2876dfa-467a-4339-8d08-e350dff0c109]
[2016-09-12 01:48:53,362: INFO/MainProcess] Task sms.tasks.add[f2876dfa-467a-4339-8d08-e350dff0c109] succeeded in 0.0008763120004005032s: 8
[2016-09-12 01:48:58,852: INFO/MainProcess] Received task: sms.tasks.add[b61b35f7-7b24-4bd2-b86e-ebb1d5011a9b]
[2016-09-12 01:48:58,853: INFO/MainProcess] Task sms.tasks.add[b61b35f7-7b24-4bd2-b86e-ebb1d5011a9b] succeeded in 0.0003789629990933463s: 8
[2016-09-12 01:49:03,793: INFO/MainProcess] Received task: sms.tasks.add[13c7a184-bd0f-430d-8cf2-fbbbdee90c64]
[2016-09-12 01:49:03,795: INFO/MainProcess] Task sms.tasks.add[13c7a184-bd0f-430d-8cf2-fbbbdee90c64] succeeded in 0.0012504879996413365s: 8
[2016-09-12 02:15:11,680: INFO/MainProcess] Received task: sms.tasks.add[92008529-9fa8-4e0e-995f-79660837934d]
[2016-09-12 02:15:11,681: INFO/MainProcess] Task sms.tasks.add[92008529-9fa8-4e0e-995f-79660837934d] succeeded in 0.00022576800074602943s: 8
[2016-09-12 02:29:35,181: INFO/MainProcess] Received task: sms.tasks.send_message[b6af0d60-8bce-49e2-8b72-dc2c78a76123] eta:[2016-09-12 22:32:00+10:00]
[2016-09-12 02:39:22,817: INFO/MainProcess] Received task: sms.tasks.send_message[9ad0bad8-d7bd-4647-9cbb-08b722847e30] eta:[2016-09-12 12:41:00+10:00]
[2016-09-12 02:41:02,852: WARNING/Worker-5] Message has been sent
[2016-09-12 02:41:02,854: INFO/MainProcess] Task sms.tasks.send_message[9ad0bad8-d7bd-4647-9cbb-08b722847e30] succeeded in 2.7260142790000828s: None
[2016-09-12 02:44:15,586: INFO/MainProcess] Received task: sms.tasks.send_message[253d7654-7629-43b6-99af-a0a3232bc8b3] eta:[2016-09-12 22:46:00+10:00]
[2016-09-12 02:48:39,613: INFO/MainProcess] Received task: sms.tasks.send_message[b3717576-7cf4-401a-b7be-be32f6f6b2b4] eta:[2016-09-12 12:50:00]
[2016-09-12 02:52:50,064: INFO/MainProcess] Received task: sms.tasks.send_message[24597483-0a14-406f-b714-8076665fe268] eta:[2016-09-12 12:53:00]
[2016-09-12 03:31:36,067: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
[2016-09-12 03:31:36,080: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2016-09-12 03:31:38,086: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2016-09-12 20:40:22,994: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-12 20:40:23,000: INFO/MainProcess] mingle: searching for neighbors
[2016-09-12 20:40:24,007: INFO/MainProcess] mingle: all alone
[2016-09-12 20:40:24,024: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-12 20:40:24,024: WARNING/MainProcess] w1@Rui ready.
[2016-09-12 20:40:24,035: INFO/MainProcess] Received task: sms.tasks.send_message[b6af0d60-8bce-49e2-8b72-dc2c78a76123] eta:[2016-09-12 22:32:00+10:00]
[2016-09-12 20:40:24,036: INFO/MainProcess] Received task: sms.tasks.send_message[253d7654-7629-43b6-99af-a0a3232bc8b3] eta:[2016-09-12 22:46:00+10:00]
[2016-09-12 20:40:24,036: INFO/MainProcess] Received task: sms.tasks.send_message[b3717576-7cf4-401a-b7be-be32f6f6b2b4] eta:[2016-09-12 12:50:00]
[2016-09-12 20:40:24,036: INFO/MainProcess] Received task: sms.tasks.send_message[24597483-0a14-406f-b714-8076665fe268] eta:[2016-09-12 12:53:00]
[2016-09-12 20:40:24,036: INFO/MainProcess] Received task: sms.tasks.add[5b3076d9-ce93-401f-aa5c-b22834a6f37e]
[2016-09-12 20:40:24,037: INFO/MainProcess] Received task: sms.tasks.add[f543558f-2101-424f-a783-604385b781dd]
[2016-09-12 20:40:24,037: INFO/MainProcess] Received task: sms.tasks.add[c3123449-f45a-4e7e-8f39-2fc6a307e93e]
[2016-09-12 20:40:24,037: INFO/MainProcess] Received task: sms.tasks.add[40b85ee3-d6c5-4feb-8c23-6ce92e43af9e]
[2016-09-12 20:40:24,037: INFO/MainProcess] Received task: sms.tasks.add[922f7262-b11d-48d9-85b4-e12e700bbb7e]
[2016-09-12 20:40:24,037: INFO/MainProcess] Received task: sms.tasks.add[56804940-fe75-48d4-9e94-838be49022f9]
[2016-09-12 20:40:24,038: INFO/MainProcess] Received task: sms.tasks.add[5bf2cb45-80dd-4986-bf5f-6824c0874289]
[2016-09-12 20:40:24,038: INFO/MainProcess] Received task: sms.tasks.add[32b507b3-a298-4d42-adce-16e5e01dc8e2]
[2016-09-12 20:40:24,038: INFO/MainProcess] Received task: sms.tasks.add[541ea6a3-5f46-463b-b4d9-2bede7105271]
[2016-09-12 20:40:24,038: INFO/MainProcess] Received task: sms.tasks.add[9451f689-ad40-4a18-a3b5-2aa790116ed6]
[2016-09-12 20:40:24,038: INFO/MainProcess] Received task: sms.tasks.add[0a09fb1b-561c-476d-9d6b-f8397c665cf5]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[47a0f228-a31e-446f-9965-d94d1bd786f7]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[15cd4181-adb1-4044-9193-8032b84c3d19]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[ea1c7655-9a9e-4ce1-8539-67be350db885]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[e49dc2f4-c685-4a28-ac3d-16337bb92ce9]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[f72d610c-a4bf-4bde-b8bf-599edc7e6c3d]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[99639fcf-c2ca-4279-83df-dfcb00b63470]
[2016-09-12 20:40:24,039: INFO/MainProcess] Received task: sms.tasks.add[284d0e79-12b5-462b-8da5-0ae071e2d2e3]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[6d61d09c-6fd8-40b7-9229-b480f1dbc163]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[ad5ac959-86f7-49c2-a5c5-ae2a9c61f963]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[61f8d60d-2a69-410e-bad5-6b5f0a6c2328]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[3eddfaec-b8aa-483f-b381-9f1480941f60]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[003d19aa-9501-4d24-b339-5ff7d81a3b41]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[08e59882-b21a-4d5f-b8e0-a82a3affcb69]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[f5778619-e796-43cd-91b1-40c85a4334ba]
[2016-09-12 20:40:24,040: INFO/MainProcess] Received task: sms.tasks.add[3ad6a50d-a683-4f04-8a95-c129ac5de1ef]
[2016-09-12 20:40:24,041: INFO/MainProcess] Received task: sms.tasks.add[0eeded1d-a9da-43ea-afa0-b4414ac1d1f4]
[2016-09-12 20:40:24,041: INFO/MainProcess] Received task: sms.tasks.add[d2207a7b-82a1-40b7-b51d-031834791397]
[2016-09-12 20:40:24,041: INFO/MainProcess] Received task: sms.tasks.add[1d919af2-9351-4fbc-a6de-a35b9c4eac42]
[2016-09-12 20:40:24,041: INFO/MainProcess] Received task: sms.tasks.add[574eeb58-70f4-4b74-b64a-67bab018e389]
[2016-09-12 20:40:26,015: INFO/MainProcess] Received task: sms.tasks.add[a0788dc9-6566-4f0b-a1ec-074c72c313b6]
[2016-09-12 20:40:26,015: INFO/MainProcess] Received task: sms.tasks.add[7e098bfa-25ab-4605-b886-e198ed6a3ebb]
[2016-09-12 20:40:26,015: INFO/MainProcess] Received task: sms.tasks.add[e691145a-f28e-42a2-9b6a-9a68e564a175]
[2016-09-12 20:40:26,015: INFO/MainProcess] Received task: sms.tasks.add[013b27bc-ffd7-442b-bad4-5d70015601b5]
[2016-09-12 20:40:26,016: INFO/MainProcess] Received task: sms.tasks.add[dfaf85a7-9e08-4c9c-948e-2032d3424e63]
[2016-09-12 20:40:26,016: INFO/MainProcess] Task sms.tasks.add[5b3076d9-ce93-401f-aa5c-b22834a6f37e] succeeded in 0.0028280669998821395s: 8
[2016-09-12 20:40:26,016: INFO/MainProcess] Task sms.tasks.add[c3123449-f45a-4e7e-8f39-2fc6a307e93e] succeeded in 0.003043108000383654s: 8
[2016-09-12 20:40:26,016: INFO/MainProcess] Task sms.tasks.add[40b85ee3-d6c5-4feb-8c23-6ce92e43af9e] succeeded in 0.003215942999759136s: 8
[2016-09-12 20:40:26,017: INFO/MainProcess] Task sms.tasks.add[f543558f-2101-424f-a783-604385b781dd] succeeded in 0.003460635999999795s: 8
[2016-09-12 20:40:26,017: INFO/MainProcess] Task sms.tasks.add[922f7262-b11d-48d9-85b4-e12e700bbb7e] succeeded in 0.0035438410000097065s: 8
[2016-09-12 20:40:26,017: INFO/MainProcess] Task sms.tasks.add[56804940-fe75-48d4-9e94-838be49022f9] succeeded in 0.0034292320001441112s: 8
[2016-09-12 20:40:26,017: INFO/MainProcess] Task sms.tasks.add[5bf2cb45-80dd-4986-bf5f-6824c0874289] succeeded in 0.003601644999889686s: 8
[2016-09-12 20:40:26,018: INFO/MainProcess] Task sms.tasks.add[32b507b3-a298-4d42-adce-16e5e01dc8e2] succeeded in 0.0037875129996791657s: 8
[2016-09-12 20:40:26,018: INFO/MainProcess] Received task: sms.tasks.add[67db04b8-10b8-4433-9d5a-f71905c515fa]
[2016-09-12 20:40:26,019: INFO/MainProcess] Received task: sms.tasks.add[564c4bac-4cc1-47ea-a522-b6547d6fdc22]
[2016-09-12 20:40:26,019: INFO/MainProcess] Received task: sms.tasks.add[6609426b-3ba8-499a-8f7c-093ef7f195b4]
[2016-09-12 20:40:26,020: INFO/MainProcess] Received task: sms.tasks.add[a9a49c48-8a14-4dfd-9ca6-a521b59c0ef6]
[2016-09-12 20:40:26,020: INFO/MainProcess] Received task: sms.tasks.add[f20721d3-74cf-4349-8b6e-190f8ad7d6bd]
[2016-09-12 20:40:26,020: INFO/MainProcess] Received task: sms.tasks.add[7474fb30-2cc1-4e74-aa15-83c13529f972]
[2016-09-12 20:40:26,020: INFO/MainProcess] Received task: sms.tasks.add[c8e6bba5-bb29-4fd0-832d-ac400590bdb9]
[2016-09-12 20:40:26,021: INFO/MainProcess] Task sms.tasks.add[ea1c7655-9a9e-4ce1-8539-67be350db885] succeeded in 0.002673414000128105s: 8
[2016-09-12 20:40:26,021: INFO/MainProcess] Task sms.tasks.add[541ea6a3-5f46-463b-b4d9-2bede7105271] succeeded in 0.0029436100003294996s: 8
[2016-09-12 20:40:26,021: INFO/MainProcess] Task sms.tasks.add[9451f689-ad40-4a18-a3b5-2aa790116ed6] succeeded in 0.00312547400017138s: 8
[2016-09-12 20:40:26,021: INFO/MainProcess] Task sms.tasks.add[0a09fb1b-561c-476d-9d6b-f8397c665cf5] succeeded in 0.003307752000182518s: 8
[2016-09-12 20:40:26,021: INFO/MainProcess] Task sms.tasks.add[47a0f228-a31e-446f-9965-d94d1bd786f7] succeeded in 0.0034724369998002658s: 8
[2016-09-12 20:40:26,022: INFO/MainProcess] Task sms.tasks.add[15cd4181-adb1-4044-9193-8032b84c3d19] succeeded in 0.003647961000297073s: 8
[2016-09-12 20:40:26,022: INFO/MainProcess] Task sms.tasks.add[e49dc2f4-c685-4a28-ac3d-16337bb92ce9] succeeded in 0.003738456000064616s: 8
[2016-09-12 20:40:26,022: INFO/MainProcess] Task sms.tasks.add[f72d610c-a4bf-4bde-b8bf-599edc7e6c3d] succeeded in 0.0039230279999173945s: 8
[2016-09-12 20:40:26,023: INFO/MainProcess] Task sms.tasks.add[99639fcf-c2ca-4279-83df-dfcb00b63470] succeeded in 0.0008243799998126633s: 8
[2016-09-12 20:40:26,023: INFO/MainProcess] Task sms.tasks.add[284d0e79-12b5-462b-8da5-0ae071e2d2e3] succeeded in 0.0010284670001965424s: 8
[2016-09-12 20:40:26,024: INFO/MainProcess] Task sms.tasks.add[6d61d09c-6fd8-40b7-9229-b480f1dbc163] succeeded in 0.0012196020002193109s: 8
[2016-09-12 20:40:26,024: INFO/MainProcess] Task sms.tasks.add[ad5ac959-86f7-49c2-a5c5-ae2a9c61f963] succeeded in 0.001391737000176363s: 8
[2016-09-12 20:40:26,024: INFO/MainProcess] Task sms.tasks.add[61f8d60d-2a69-410e-bad5-6b5f0a6c2328] succeeded in 0.00156238099998518s: 8
[2016-09-12 20:40:26,024: INFO/MainProcess] Task sms.tasks.add[3eddfaec-b8aa-483f-b381-9f1480941f60] succeeded in 0.001729518000047392s: 8
[2016-09-12 20:40:26,024: INFO/MainProcess] Task sms.tasks.add[003d19aa-9501-4d24-b339-5ff7d81a3b41] succeeded in 0.0018401769998490636s: 8
[2016-09-12 20:40:26,025: INFO/MainProcess] Task sms.tasks.add[08e59882-b21a-4d5f-b8e0-a82a3affcb69] succeeded in 0.00203034000014668s: 8
[2016-09-12 20:40:26,026: INFO/MainProcess] Task sms.tasks.add[f5778619-e796-43cd-91b1-40c85a4334ba] succeeded in 0.0008627080001133436s: 8
[2016-09-12 20:40:26,026: INFO/MainProcess] Task sms.tasks.add[0eeded1d-a9da-43ea-afa0-b4414ac1d1f4] succeeded in 0.0010404760000710667s: 8
[2016-09-12 20:40:26,026: INFO/MainProcess] Task sms.tasks.add[3ad6a50d-a683-4f04-8a95-c129ac5de1ef] succeeded in 0.0011991010001111135s: 8
[2016-09-12 20:40:26,026: INFO/MainProcess] Task sms.tasks.add[d2207a7b-82a1-40b7-b51d-031834791397] succeeded in 0.0013382789998104272s: 8
[2016-09-12 20:40:26,026: INFO/MainProcess] Task sms.tasks.add[1d919af2-9351-4fbc-a6de-a35b9c4eac42] succeeded in 0.0014738419999957841s: 8
[2016-09-12 20:40:26,027: INFO/MainProcess] Task sms.tasks.add[574eeb58-70f4-4b74-b64a-67bab018e389] succeeded in 0.001607103999958781s: 8
[2016-09-12 20:40:26,028: INFO/MainProcess] Task sms.tasks.add[a0788dc9-6566-4f0b-a1ec-074c72c313b6] succeeded in 0.0010439030002089567s: 8
[2016-09-12 20:40:26,028: INFO/MainProcess] Task sms.tasks.add[7e098bfa-25ab-4605-b886-e198ed6a3ebb] succeeded in 0.0012443480000001728s: 8
[2016-09-12 20:40:26,028: INFO/MainProcess] Task sms.tasks.add[e691145a-f28e-42a2-9b6a-9a68e564a175] succeeded in 0.0011223890001019754s: 8
[2016-09-12 20:40:26,028: INFO/MainProcess] Task sms.tasks.add[013b27bc-ffd7-442b-bad4-5d70015601b5] succeeded in 0.0012586950001605146s: 8
[2016-09-12 20:40:26,029: INFO/MainProcess] Task sms.tasks.add[dfaf85a7-9e08-4c9c-948e-2032d3424e63] succeeded in 0.0013803030001326988s: 8
[2016-09-12 20:40:26,029: INFO/MainProcess] Task sms.tasks.add[67db04b8-10b8-4433-9d5a-f71905c515fa] succeeded in 0.001511697000296408s: 8
[2016-09-12 20:40:26,029: INFO/MainProcess] Task sms.tasks.add[a9a49c48-8a14-4dfd-9ca6-a521b59c0ef6] succeeded in 0.00044825899976785877s: 8
[2016-09-12 20:40:26,029: INFO/MainProcess] Task sms.tasks.add[f20721d3-74cf-4349-8b6e-190f8ad7d6bd] succeeded in 0.000566544999855978s: 8
[2016-09-12 20:40:26,030: INFO/MainProcess] Task sms.tasks.add[7474fb30-2cc1-4e74-aa15-83c13529f972] succeeded in 0.0006940749999557738s: 8
[2016-09-12 20:40:26,030: INFO/MainProcess] Task sms.tasks.add[c8e6bba5-bb29-4fd0-832d-ac400590bdb9] succeeded in 0.0007759380000607052s: 8
[2016-09-12 20:40:28,094: WARNING/Worker-4] Message has been sent
[2016-09-12 20:40:28,095: INFO/MainProcess] Task sms.tasks.send_message[24597483-0a14-406f-b714-8076665fe268] succeeded in 2.069804865000151s: None
[2016-09-12 20:40:28,095: INFO/MainProcess] Task sms.tasks.add[6609426b-3ba8-499a-8f7c-093ef7f195b4] succeeded in 0.0006086680000407796s: 8
[2016-09-12 20:40:28,098: WARNING/Worker-6] Message has been sent
[2016-09-12 20:40:28,098: INFO/MainProcess] Task sms.tasks.send_message[b3717576-7cf4-401a-b7be-be32f6f6b2b4] succeeded in 2.0731491179999466s: None
[2016-09-12 20:40:28,099: INFO/MainProcess] Task sms.tasks.add[564c4bac-4cc1-47ea-a522-b6547d6fdc22] succeeded in 0.0006071530001463543s: 8
[2016-09-12 20:53:58,434: INFO/MainProcess] Received task: sms.tasks.send_message[fd4239d4-b8cf-48f4-a316-6a763a5aa1e7] eta:[2016-09-12 20:54:00]
[2016-09-12 20:54:03,190: WARNING/Worker-8] Message has been sent
[2016-09-12 20:54:03,191: INFO/MainProcess] Task sms.tasks.send_message[fd4239d4-b8cf-48f4-a316-6a763a5aa1e7] succeeded in 2.0113339389999965s: None
[2016-09-12 20:54:25,852: INFO/MainProcess] Received task: sms.tasks.send_message[8be24bb4-603a-4ad2-a07a-18dfe9974c17] eta:[2016-09-12 20:56:00]
[2016-09-12 20:56:03,099: WARNING/Worker-5] Message has been sent
[2016-09-12 20:56:03,101: INFO/MainProcess] Task sms.tasks.send_message[8be24bb4-603a-4ad2-a07a-18dfe9974c17] succeeded in 1.7295878099998845s: None
[2016-09-12 21:02:57,374: INFO/MainProcess] Received task: sms.tasks.send_message[61320a1b-9126-48b3-890f-66ed83bcc575] eta:[2016-09-12 21:05:00]
[2016-09-12 21:05:02,041: WARNING/Worker-6] Message has been sent
[2016-09-12 21:05:02,042: INFO/MainProcess] Task sms.tasks.send_message[61320a1b-9126-48b3-890f-66ed83bcc575] succeeded in 1.8669986039999458s: None
[2016-09-12 22:20:40,918: INFO/MainProcess] Received task: sms.tasks.add[3c74144f-799c-4573-8712-5b40528dd320]
[2016-09-12 22:20:40,919: INFO/MainProcess] Task sms.tasks.add[3c74144f-799c-4573-8712-5b40528dd320] succeeded in 0.0002756329995463602s: 8
[2016-09-12 22:32:02,002: WARNING/Worker-3] HTTP 401 error: Authenticate
[2016-09-12 22:32:02,003: INFO/MainProcess] Task sms.tasks.send_message[b6af0d60-8bce-49e2-8b72-dc2c78a76123] succeeded in 1.820722910000768s: None
[2016-09-12 22:37:56,144: INFO/MainProcess] Received task: sms.tasks.add[47a49331-c763-40f7-b4d6-8a66191abddf]
[2016-09-12 22:37:56,145: INFO/MainProcess] Task sms.tasks.add[47a49331-c763-40f7-b4d6-8a66191abddf] succeeded in 0.0003827399996225722s: 8
[2016-09-12 22:43:10,267: INFO/MainProcess] Received task: sms.tasks.add[6eb8adc8-71e9-44f2-8474-33960b68fa2d]
[2016-09-12 22:43:10,268: INFO/MainProcess] Task sms.tasks.add[6eb8adc8-71e9-44f2-8474-33960b68fa2d] succeeded in 0.00024206400121329352s: 8
[2016-09-12 22:43:27,904: INFO/MainProcess] Received task: sms.tasks.add[f3837dd9-5a82-4107-8b88-f35eb0902b9f]
[2016-09-12 22:43:27,905: INFO/MainProcess] Task sms.tasks.add[f3837dd9-5a82-4107-8b88-f35eb0902b9f] succeeded in 0.000623157000518404s: 8
[2016-09-12 22:45:42,072: INFO/MainProcess] Received task: sms.tasks.add[97034f5a-7596-4c1d-8440-527c764abf0a]
[2016-09-12 22:45:42,073: INFO/MainProcess] Task sms.tasks.add[97034f5a-7596-4c1d-8440-527c764abf0a] succeeded in 0.0002799140002025524s: 8
[2016-09-12 22:45:44,198: INFO/MainProcess] Received task: sms.tasks.add[14d91dec-e41b-442b-af4b-0282af8b3137]
[2016-09-12 22:45:44,199: INFO/MainProcess] Task sms.tasks.add[14d91dec-e41b-442b-af4b-0282af8b3137] succeeded in 0.0002596770009404281s: 8
[2016-09-12 22:46:05,650: INFO/MainProcess] Received task: sms.tasks.add[d6d86a08-9daa-48d7-8603-8287e1560250]
[2016-09-12 22:46:05,651: INFO/MainProcess] Task sms.tasks.add[d6d86a08-9daa-48d7-8603-8287e1560250] succeeded in 0.00048038400018413085s: 8
[2016-09-12 22:46:28,216: INFO/MainProcess] Received task: sms.tasks.add[20b11be8-6065-48ba-bd05-0b35efddc864]
[2016-09-12 22:46:28,220: INFO/MainProcess] Task sms.tasks.add[20b11be8-6065-48ba-bd05-0b35efddc864] succeeded in 0.00277124000058393s: 8
[2016-09-12 22:46:32,079: WARNING/Worker-6] Message has been sent
[2016-09-12 22:46:32,080: INFO/MainProcess] Task sms.tasks.send_message[253d7654-7629-43b6-99af-a0a3232bc8b3] succeeded in 30.653876616999696s: None
[2016-09-12 22:46:40,282: INFO/MainProcess] Received task: sms.tasks.add[1052fbca-4609-4215-8dc9-250941c7a894]
[2016-09-12 22:46:40,283: INFO/MainProcess] Task sms.tasks.add[1052fbca-4609-4215-8dc9-250941c7a894] succeeded in 0.0006913090001035016s: 8
[2016-09-12 22:59:32,961: INFO/MainProcess] Received task: sms.tasks.add[264de82b-9004-45ed-b3e6-ea2441d299d0]
[2016-09-12 22:59:32,963: INFO/MainProcess] Task sms.tasks.add[264de82b-9004-45ed-b3e6-ea2441d299d0] succeeded in 0.000486613000248326s: 8
[2016-09-12 22:59:53,918: INFO/MainProcess] Received task: sms.tasks.add[7333db74-79a3-484e-802e-a349e7577651]
[2016-09-12 22:59:53,918: INFO/MainProcess] Task sms.tasks.add[7333db74-79a3-484e-802e-a349e7577651] succeeded in 0.00022141000044939574s: 8
[2016-09-12 23:20:16,261: INFO/MainProcess] Received task: sms.tasks.add[0323cb96-894a-42ab-b4fd-d321a0ec82a2]
[2016-09-12 23:20:16,262: INFO/MainProcess] Task sms.tasks.add[0323cb96-894a-42ab-b4fd-d321a0ec82a2] succeeded in 0.00024705699979676865s: 8
[2016-09-12 23:20:56,317: INFO/MainProcess] Received task: sms.tasks.add[6ada0c03-c224-432d-a0f5-509f776b92eb]
[2016-09-12 23:20:56,318: INFO/MainProcess] Task sms.tasks.add[6ada0c03-c224-432d-a0f5-509f776b92eb] succeeded in 0.00032411499887530226s: 8
[2016-09-12 23:22:38,019: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
[2016-09-12 23:22:38,032: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2016-09-12 23:22:40,039: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2016-09-13 12:42:43,308: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-13 12:42:43,315: INFO/MainProcess] mingle: searching for neighbors
[2016-09-13 12:42:44,322: INFO/MainProcess] mingle: all alone
[2016-09-13 12:42:44,341: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-13 12:42:44,342: WARNING/MainProcess] w1@Rui ready.
[2016-09-13 12:42:44,343: INFO/MainProcess] Received task: sms.tasks.add[1e1cb6f6-d407-472b-a3ac-7f496e933731]
[2016-09-13 12:42:44,344: INFO/MainProcess] Task sms.tasks.add[1e1cb6f6-d407-472b-a3ac-7f496e933731] succeeded in 0.0004212179992464371s: 8
[2016-09-13 12:44:04,250: INFO/MainProcess] Received task: sms.tasks.send_message[d8777af6-c881-4221-946c-07231699997a] eta:[2016-02-13 12:45:00]
[2016-09-13 12:44:06,207: WARNING/Worker-8] Message has been sent
[2016-09-13 12:44:06,208: INFO/MainProcess] Task sms.tasks.send_message[d8777af6-c881-4221-946c-07231699997a] succeeded in 1.833609912000611s: None
[2016-09-13 12:45:09,287: INFO/MainProcess] Received task: sms.tasks.send_message[2b6d8d58-402b-4689-971f-ed2522b9b64d] eta:[2016-02-13 12:47:00]
[2016-09-13 12:45:10,782: WARNING/Worker-7] Message has been sent
[2016-09-13 12:45:10,783: INFO/MainProcess] Task sms.tasks.send_message[2b6d8d58-402b-4689-971f-ed2522b9b64d] succeeded in 1.3828708290002396s: None
[2016-09-13 12:46:33,258: INFO/MainProcess] Received task: sms.tasks.send_message[24220a74-1f4c-435e-b330-fc5caa7837ef] eta:[2016-02-13 12:50:00]
[2016-09-13 12:46:35,900: WARNING/Worker-4] Message has been sent
[2016-09-13 12:46:35,900: INFO/MainProcess] Task sms.tasks.send_message[24220a74-1f4c-435e-b330-fc5caa7837ef] succeeded in 1.464470495000569s: None
[2016-09-13 12:51:19,959: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
[2016-09-13 12:51:19,971: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2016-09-13 12:51:21,982: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2016-09-13 20:53:36,771: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-13 20:53:36,777: INFO/MainProcess] mingle: searching for neighbors
[2016-09-13 20:53:37,783: INFO/MainProcess] mingle: all alone
[2016-09-13 20:53:37,810: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-13 20:53:37,811: WARNING/MainProcess] w1@Rui ready.
[2016-09-13 20:55:17,203: INFO/MainProcess] Received task: sms.tasks.add[d1e98cc9-02a5-4ad9-abf3-03fd46c11f64]
[2016-09-13 20:55:17,205: INFO/MainProcess] Task sms.tasks.add[d1e98cc9-02a5-4ad9-abf3-03fd46c11f64] succeeded in 0.00044010099998104124s: 8
[2016-09-13 20:55:46,114: INFO/MainProcess] Received task: sms.tasks.send_message[290c8a7e-6913-47c5-a921-aeb11492810c] eta:[2016-09-13 20:57:00]
[2016-09-13 20:55:46,115: INFO/MainProcess] Received task: sms.tasks.send_message[d40d8858-948f-49b7-a8a3-77975b56de63]
[2016-09-13 20:55:49,121: WARNING/Worker-3] Message has been sent
[2016-09-13 20:55:49,122: INFO/MainProcess] Task sms.tasks.send_message[d40d8858-948f-49b7-a8a3-77975b56de63] succeeded in 1.904748350000034s: None
[2016-09-13 20:57:03,181: WARNING/Worker-6] Message has been sent
[2016-09-13 20:57:03,181: INFO/MainProcess] Task sms.tasks.send_message[290c8a7e-6913-47c5-a921-aeb11492810c] succeeded in 1.8417988109999897s: None
[2016-09-13 21:00:14,145: INFO/MainProcess] Received task: sms.tasks.send_message[0289e3f9-6d63-4fd0-8b8a-05a6a39c8fef] eta:[2016-09-13 21:03:00]
[2016-09-13 21:00:14,145: INFO/MainProcess] Received task: sms.tasks.send_message[2fd20db1-1e6c-4c2b-85ca-9bcbe4c53996]
[2016-09-13 21:00:20,223: WARNING/Worker-7] Message has been sent
[2016-09-13 21:00:20,225: INFO/MainProcess] Task sms.tasks.send_message[2fd20db1-1e6c-4c2b-85ca-9bcbe4c53996] succeeded in 4.627337537000017s: None
[2016-09-13 21:03:03,742: WARNING/Worker-4] Message has been sent
[2016-09-13 21:03:03,742: INFO/MainProcess] Task sms.tasks.send_message[0289e3f9-6d63-4fd0-8b8a-05a6a39c8fef] succeeded in 1.9014695319999646s: None
[2016-09-13 22:01:44,032: INFO/MainProcess] Received task: sms.tasks.add[eb560d4b-3540-427a-a520-316ae5101eeb]
[2016-09-13 22:01:44,034: INFO/MainProcess] Task sms.tasks.add[eb560d4b-3540-427a-a520-316ae5101eeb] succeeded in 0.0009408329997313558s: 8
[2016-09-13 22:02:14,417: INFO/MainProcess] Received task: sms.tasks.add[d8bf9552-7bce-46df-be83-3100b311a614]
[2016-09-13 22:02:14,418: INFO/MainProcess] Task sms.tasks.add[d8bf9552-7bce-46df-be83-3100b311a614] succeeded in 0.00046046100032981485s: 8
[2016-09-13 22:02:27,073: INFO/MainProcess] Received task: sms.tasks.add[6b6f6cca-be5d-4d2d-b826-82e43fe5acd8]
[2016-09-13 22:02:27,074: INFO/MainProcess] Task sms.tasks.add[6b6f6cca-be5d-4d2d-b826-82e43fe5acd8] succeeded in 0.00035864199981006095s: 8
[2016-09-13 22:02:35,920: INFO/MainProcess] Received task: sms.tasks.add[01c2c73e-d7cd-43c8-869c-e4b2b7369f2c]
[2016-09-13 22:02:35,922: INFO/MainProcess] Task sms.tasks.add[01c2c73e-d7cd-43c8-869c-e4b2b7369f2c] succeeded in 0.0005257829998299712s: 8
[2016-09-13 22:08:22,164: INFO/MainProcess] Received task: sms.tasks.add[bbd19a93-de9e-467d-9036-7f25e9f60759]
[2016-09-13 22:08:22,165: INFO/MainProcess] Task sms.tasks.add[bbd19a93-de9e-467d-9036-7f25e9f60759] succeeded in 0.00033127300048363395s: 8
[2016-09-13 22:31:00,081: INFO/MainProcess] Received task: sms.tasks.add[aa0431a6-8e66-4b6d-a003-fc53a39b260d]
[2016-09-13 22:31:00,082: INFO/MainProcess] Task sms.tasks.add[aa0431a6-8e66-4b6d-a003-fc53a39b260d] succeeded in 0.00032291499974235194s: 8
[2016-09-13 23:27:04,675: INFO/MainProcess] Received task: sms.tasks.add[2e88104a-b0f9-411b-9abd-9a4d9f2baa36]
[2016-09-13 23:27:04,677: INFO/MainProcess] Task sms.tasks.add[2e88104a-b0f9-411b-9abd-9a4d9f2baa36] succeeded in 0.0006111319999035913s: 8
[2016-09-13 23:37:55,717: INFO/MainProcess] Received task: sms.tasks.send_message[ca3fcb26-744c-4342-8c0e-1d18b3f39695] eta:[2016-09-13 23:39:00]
[2016-09-13 23:37:55,718: INFO/MainProcess] Received task: sms.tasks.send_message[a24576b7-6402-455b-83dd-66d2f11703a1]
[2016-09-13 23:37:57,602: WARNING/Worker-4] Message has been sent
[2016-09-13 23:37:57,603: INFO/MainProcess] Task sms.tasks.send_message[a24576b7-6402-455b-83dd-66d2f11703a1] succeeded in 1.881720683999447s: None
[2016-09-13 23:39:02,551: WARNING/Worker-1] Message has been sent
[2016-09-13 23:39:02,554: INFO/MainProcess] Task sms.tasks.send_message[ca3fcb26-744c-4342-8c0e-1d18b3f39695] succeeded in 1.8069231739991665s: None
[2016-09-13 23:43:05,060: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
[2016-09-13 23:43:05,071: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2016-09-13 23:43:07,078: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2016-09-15 19:51:23,849: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-15 19:51:23,858: INFO/MainProcess] mingle: searching for neighbors
[2016-09-15 19:51:24,864: INFO/MainProcess] mingle: all alone
[2016-09-15 19:51:24,880: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-15 19:51:24,880: WARNING/MainProcess] w1@Rui ready.
[2016-09-15 19:51:24,882: INFO/MainProcess] Received task: sms.tasks.add[904aaf33-aa5e-400e-bb47-a1807c1afa8f]
[2016-09-15 19:51:24,883: INFO/MainProcess] Task sms.tasks.add[904aaf33-aa5e-400e-bb47-a1807c1afa8f] succeeded in 0.0003833459999924571s: 8
[2016-09-15 19:51:26,881: INFO/MainProcess] Received task: sms.tasks.add[ff333363-292c-48b5-b713-38b6f833ce56]
[2016-09-15 19:51:26,881: INFO/MainProcess] Received task: sms.tasks.add[f123778f-510c-4969-a033-cf2ea6979d0f]
[2016-09-15 19:51:26,882: INFO/MainProcess] Received task: sms.tasks.add[07892ffe-cf1d-4acb-9956-0ed8245c272f]
[2016-09-15 19:51:26,882: INFO/MainProcess] Received task: sms.tasks.add[ef27102b-a03f-4471-a2c1-f8766d59ad7e]
[2016-09-15 19:51:26,882: INFO/MainProcess] Received task: sms.tasks.add[7b8fd896-b803-4f90-97da-eda9ea1fafe6]
[2016-09-15 19:51:26,882: INFO/MainProcess] Received task: sms.tasks.add[b8970b71-102b-4fcb-9e7f-cfd96d4010b2]
[2016-09-15 19:51:26,883: INFO/MainProcess] Received task: sms.tasks.add[55875958-bdbb-49cb-a926-502e4d49d350]
[2016-09-15 19:51:26,883: INFO/MainProcess] Received task: sms.tasks.send_message[ca06a495-e1da-4ada-8304-5a87538d20dc] eta:[2016-09-14 17:15:00]
[2016-09-15 19:51:26,883: INFO/MainProcess] Received task: sms.tasks.send_message[09eac10e-665f-4eb8-ab4b-b4670a924d1e]
[2016-09-15 19:51:26,884: INFO/MainProcess] Task sms.tasks.add[f123778f-510c-4969-a033-cf2ea6979d0f] succeeded in 0.0004327709999927265s: 8
[2016-09-15 19:51:26,884: INFO/MainProcess] Task sms.tasks.add[ff333363-292c-48b5-b713-38b6f833ce56] succeeded in 0.0007167540000097006s: 8
[2016-09-15 19:51:26,884: INFO/MainProcess] Task sms.tasks.add[07892ffe-cf1d-4acb-9956-0ed8245c272f] succeeded in 0.0008293650000013031s: 8
[2016-09-15 19:51:26,885: INFO/MainProcess] Task sms.tasks.add[7b8fd896-b803-4f90-97da-eda9ea1fafe6] succeeded in 0.0008067759999903501s: 8
[2016-09-15 19:51:26,885: INFO/MainProcess] Task sms.tasks.add[55875958-bdbb-49cb-a926-502e4d49d350] succeeded in 0.0008184679999914124s: 8
[2016-09-15 19:51:26,885: INFO/MainProcess] Task sms.tasks.add[b8970b71-102b-4fcb-9e7f-cfd96d4010b2] succeeded in 0.000838716999993494s: 8
[2016-09-15 19:51:26,886: INFO/MainProcess] Task sms.tasks.add[ef27102b-a03f-4471-a2c1-f8766d59ad7e] succeeded in 0.0006537940000015396s: 8
[2016-09-15 19:51:26,887: ERROR/MainProcess] Task sms.tasks.send_message[ca06a495-e1da-4ada-8304-5a87538d20dc] raised unexpected: TypeError('send_message() takes 1 positional argument but 3 were given',)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: send_message() takes 1 positional argument but 3 were given
[2016-09-15 19:51:26,887: ERROR/MainProcess] Task sms.tasks.send_message[09eac10e-665f-4eb8-ab4b-b4670a924d1e] raised unexpected: TypeError('send_message() takes 1 positional argument but 3 were given',)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: send_message() takes 1 positional argument but 3 were given
[2016-09-15 19:53:42,117: INFO/MainProcess] Received task: sms.tasks.send_message[3fb4d2f6-37b5-417c-89f0-9506a7f88805] eta:[2016-09-15 19:55:00+10:00]
[2016-09-15 19:55:01,176: ERROR/MainProcess] Task sms.tasks.send_message[3fb4d2f6-37b5-417c-89f0-9506a7f88805] raised unexpected: AttributeError("'QuerySet' object has no attribute 'content'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 46, in send_message
    body = sms_object.content
AttributeError: 'QuerySet' object has no attribute 'content'
[2016-09-15 19:58:55,756: INFO/MainProcess] Received task: sms.tasks.send_message[406ada33-237a-42bc-964f-7ce9c5ff348a] eta:[2016-09-15 20:00:27+10:00]
[2016-09-15 20:00:27,653: ERROR/MainProcess] Task sms.tasks.send_message[406ada33-237a-42bc-964f-7ce9c5ff348a] raised unexpected: AttributeError("'QuerySet' object has no attribute 'content'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 46, in send_message
    body = sms_object.content
AttributeError: 'QuerySet' object has no attribute 'content'
[2016-09-15 20:02:29,062: INFO/MainProcess] Received task: sms.tasks.send_message[e0e1a9a2-cc4c-488c-8515-daeb40853d8e]
[2016-09-15 20:02:29,066: ERROR/MainProcess] Task sms.tasks.send_message[e0e1a9a2-cc4c-488c-8515-daeb40853d8e] raised unexpected: AttributeError("'QuerySet' object has no attribute 'content'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 46, in send_message
    body = sms_object.content
AttributeError: 'QuerySet' object has no attribute 'content'
[2016-09-15 20:03:48,480: INFO/MainProcess] Received task: sms.tasks.send_message[24d216a5-b269-48de-b7d6-61a3c23a919e]
[2016-09-15 20:03:48,483: ERROR/MainProcess] Task sms.tasks.send_message[24d216a5-b269-48de-b7d6-61a3c23a919e] raised unexpected: AttributeError("'QuerySet' object has no attribute 'content'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 46, in send_message
    body = sms_object.content
AttributeError: 'QuerySet' object has no attribute 'content'
[2016-09-15 20:12:06,862: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-15 20:12:06,869: INFO/MainProcess] mingle: searching for neighbors
[2016-09-15 20:12:07,875: INFO/MainProcess] mingle: all alone
[2016-09-15 20:12:07,882: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-15 20:12:07,882: WARNING/MainProcess] w1@Rui ready.
[2016-09-15 20:12:47,641: INFO/MainProcess] Received task: sms.tasks.send_message[706bf068-8f05-43d7-a754-af40e8ca64c7]
[2016-09-15 20:12:47,650: ERROR/MainProcess] Task sms.tasks.send_message[706bf068-8f05-43d7-a754-af40e8ca64c7] raised unexpected: AttributeError("'SMS' object has no attribute 'receiver_area_code'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 47, in send_message
    to = sms_object.receiver_area_code + str(sms_object.receiver_number)
AttributeError: 'SMS' object has no attribute 'receiver_area_code'
[2016-09-15 20:13:52,028: INFO/MainProcess] Received task: sms.tasks.send_message[b45d503c-f823-4d37-a9df-dfb044522e1d]
[2016-09-15 20:13:52,033: ERROR/MainProcess] Task sms.tasks.send_message[b45d503c-f823-4d37-a9df-dfb044522e1d] raised unexpected: AttributeError("'SMS' object has no attribute 'receiver_area_code'",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 47, in send_message
    to = sms_object.receiver_areacode + str(sms_object.receiver_number)
AttributeError: 'SMS' object has no attribute 'receiver_area_code'
[2016-09-15 20:14:25,864: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-15 20:14:25,870: INFO/MainProcess] mingle: searching for neighbors
[2016-09-15 20:14:26,877: INFO/MainProcess] mingle: all alone
[2016-09-15 20:14:26,885: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-15 20:14:26,885: WARNING/MainProcess] w1@Rui ready.
[2016-09-15 20:15:13,049: INFO/MainProcess] Received task: sms.tasks.send_message[06356d9a-1bb3-40ea-942f-490bdd6000d5]
[2016-09-15 20:15:14,947: WARNING/Worker-3] Message has been sent.
[2016-09-15 20:15:14,947: INFO/MainProcess] Task sms.tasks.send_message[06356d9a-1bb3-40ea-942f-490bdd6000d5] succeeded in 1.896855134000134s: None
[2016-09-15 20:17:27,347: INFO/MainProcess] Received task: sms.tasks.send_message[db8217b8-02d0-4293-ba70-cc3e6cdac83e] eta:[2016-09-15 20:20:13+10:00]
[2016-09-15 20:20:15,128: WARNING/Worker-2] Message has been sent.
[2016-09-15 20:20:15,129: INFO/MainProcess] Task sms.tasks.send_message[db8217b8-02d0-4293-ba70-cc3e6cdac83e] succeeded in 1.7377756280000085s: None
[2016-09-15 20:24:21,112: INFO/MainProcess] Received task: sms.tasks.send_message[9fb4c538-7574-4e68-a3a6-b37acd0ac3ad] eta:[2016-09-15 20:20:13+10:00]
[2016-09-15 20:24:23,597: WARNING/Worker-5] Message has been sent.
[2016-09-15 20:24:23,598: INFO/MainProcess] Task sms.tasks.send_message[9fb4c538-7574-4e68-a3a6-b37acd0ac3ad] succeeded in 1.8465863569999783s: None
[2016-09-15 22:47:41,279: INFO/MainProcess] Received task: sms.tasks.send_message[1ef10047-8e48-42e2-904d-cf3e98f32dd4] eta:[2016-09-15 22:50:19+10:00]
[2016-09-15 22:47:41,290: ERROR/MainProcess] Received unregistered task of type 'sms.tasks.send_message_immediately'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{'retries': 0, 'utc': False, 'chord': None, 'taskset': None, 'expires': None, 'args': (10, datetime.datetime(2016, 9, 15, 22, 50, 19, tzinfo=<DstTzInfo 'Australia/Melbourne' AEST+10:00:00 STD>)), 'id': '3842723c-fb75-481d-837a-d79469434659', 'timelimit': (None, None), 'callbacks': None, 'task': 'sms.tasks.send_message_immediately', 'errbacks': None, 'kwargs': {}, 'eta': None} (421b)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 456, in on_task_received
    strategies[name](message, body,
KeyError: 'sms.tasks.send_message_immediately'
[2016-09-15 22:49:21,406: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-15 22:49:21,413: INFO/MainProcess] mingle: searching for neighbors
[2016-09-15 22:49:22,419: INFO/MainProcess] mingle: all alone
[2016-09-15 22:49:22,432: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-15 22:49:22,432: WARNING/MainProcess] w1@Rui ready.
[2016-09-15 22:49:22,433: INFO/MainProcess] Received task: sms.tasks.send_message[1ef10047-8e48-42e2-904d-cf3e98f32dd4] eta:[2016-09-15 22:50:19+10:00]
[2016-09-15 22:49:43,233: INFO/MainProcess] Received task: sms.tasks.send_message[1eb90110-20f3-42ab-b55d-9f32374b65d4] eta:[2016-09-15 22:50:27+10:00]
[2016-09-15 22:49:43,243: INFO/MainProcess] Received task: sms.tasks.send_message_immediately[b8d239e9-4587-4e1d-b04a-da65aa219133]
[2016-09-15 22:49:44,467: ERROR/MainProcess] Task sms.tasks.send_message_immediately[b8d239e9-4587-4e1d-b04a-da65aa219133] raised unexpected: TypeError("Can't convert 'datetime.datetime' object to str implicitly",)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/PycharmProjects/nightshiftworker/sms/tasks.py", line 69, in send_message_immediately
    body = "A message to " + str(to) + " scheduled at " + eta + " has been set. If this is not done" \
TypeError: Can't convert 'datetime.datetime' object to str implicitly
[2016-09-15 22:50:22,381: WARNING/Worker-8] Message has been sent.
[2016-09-15 22:50:22,382: INFO/MainProcess] Task sms.tasks.send_message[1ef10047-8e48-42e2-904d-cf3e98f32dd4] succeeded in 1.8771628289996443s: None
[2016-09-15 22:50:28,992: WARNING/Worker-5] Message has been sent.
[2016-09-15 22:50:28,993: INFO/MainProcess] Task sms.tasks.send_message[1eb90110-20f3-42ab-b55d-9f32374b65d4] succeeded in 1.5412778959998832s: None
[2016-09-15 22:52:28,818: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-09-15 22:52:28,826: INFO/MainProcess] mingle: searching for neighbors
[2016-09-15 22:52:29,832: INFO/MainProcess] mingle: all alone
[2016-09-15 22:52:29,840: WARNING/MainProcess] /home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2016-09-15 22:52:29,840: WARNING/MainProcess] w1@Rui ready.
[2016-09-15 22:52:53,501: INFO/MainProcess] Received task: sms.tasks.send_message[5eea6539-1add-4e9e-a3a1-4ce6e1d268d5] eta:[2016-09-15 22:55:35+10:00]
[2016-09-15 22:52:53,511: INFO/MainProcess] Received task: sms.tasks.send_message_immediately[8b23b687-d05e-4488-9d76-3a13d517d014]
[2016-09-15 22:52:55,259: WARNING/Worker-6] HTTP 400 error: The 'To' number 12 is not a valid phone number.
[2016-09-15 22:52:55,259: INFO/MainProcess] Task sms.tasks.send_message_immediately[8b23b687-d05e-4488-9d76-3a13d517d014] succeeded in 1.3744572030009294s: None
[2016-09-15 22:55:16,286: INFO/MainProcess] Received task: sms.tasks.send_message[0c942d6b-58c9-4afb-bba7-aa066d5ca3c7] eta:[2016-09-15 23:00:53+10:00]
[2016-09-15 22:55:16,287: INFO/MainProcess] Received task: sms.tasks.send_message_immediately[82745f17-2cb4-482c-bb1f-0e982802022b]
[2016-09-15 22:55:19,780: WARNING/Worker-2] Message has been sent.
[2016-09-15 22:55:19,781: INFO/MainProcess] Task sms.tasks.send_message_immediately[82745f17-2cb4-482c-bb1f-0e982802022b] succeeded in 1.7017869020000944s: None
[2016-09-15 22:55:37,650: WARNING/Worker-1] Message has been sent.
[2016-09-15 22:55:37,651: INFO/MainProcess] Task sms.tasks.send_message[5eea6539-1add-4e9e-a3a1-4ce6e1d268d5] succeeded in 1.5508693940009834s: None
[2016-09-15 23:01:00,321: WARNING/Worker-8] Message has been sent.
[2016-09-15 23:01:00,322: INFO/MainProcess] Task sms.tasks.send_message[0c942d6b-58c9-4afb-bba7-aa066d5ca3c7] succeeded in 5.7317156810004235s: None
[2016-09-15 23:10:00,221: INFO/MainProcess] Received task: sms.tasks.send_message[9633a821-3070-4f37-a6fc-4076c5847793] eta:[2016-09-15 23:15:32+10:00]
[2016-09-15 23:10:00,222: INFO/MainProcess] Received task: sms.tasks.send_message_immediately[bd0ad579-f22a-47cc-a750-35b91fb0b02c]
[2016-09-15 23:10:02,336: WARNING/Worker-5] Message has been sent.
[2016-09-15 23:10:02,338: INFO/MainProcess] Task sms.tasks.send_message_immediately[bd0ad579-f22a-47cc-a750-35b91fb0b02c] succeeded in 2.096709343000839s: None
[2016-09-15 23:15:33,911: WARNING/Worker-3] Message has been cancalled.
[2016-09-15 23:15:33,912: INFO/MainProcess] Task sms.tasks.send_message[9633a821-3070-4f37-a6fc-4076c5847793] succeeded in 0.005673654999554856s: None
[2016-09-15 23:37:53,157: INFO/MainProcess] Received task: sms.tasks.send_message[fbc1b6d2-834c-46d9-8515-3f83234829fe] eta:[2016-09-15 23:40:22+10:00]
[2016-09-15 23:37:53,158: INFO/MainProcess] Received task: sms.tasks.send_message_immediately[f8f88136-44ac-4804-bb24-60f8c5a339b8]
[2016-09-15 23:37:55,770: WARNING/Worker-4] Message has been sent.
[2016-09-15 23:37:55,772: INFO/MainProcess] Task sms.tasks.send_message_immediately[f8f88136-44ac-4804-bb24-60f8c5a339b8] succeeded in 1.892642609000177s: None
[2016-09-15 23:40:22,084: WARNING/Worker-7] Message has been cancalled.
[2016-09-15 23:40:22,085: INFO/MainProcess] Task sms.tasks.send_message[fbc1b6d2-834c-46d9-8515-3f83234829fe] succeeded in 0.003762479000215535s: None
[2016-09-15 23:54:44,040: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/PycharmProjects/nightshiftworker/local/lib/python3.4/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
[2016-09-15 23:54:44,054: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2016-09-15 23:54:46,061: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

